#!/bin/bash
# ============================================================
# setup.sh — EMR System v2 Setup Script
# Barangay Veinte Reales & Barangay Dalandanan
#
# Usage:
#   bash setup.sh
#   bash setup.sh dalandanan     (para sa Dalandanan instance)
# ============================================================

set -e

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# --- Determine which barangay ---
BARANGAY_ARG="${1:-vientereales}"

if [[ "$BARANGAY_ARG" == "dalandanan" ]]; then
    BARANGAY_DB="emr_dalandanan"
    BARANGAY_NAME="Barangay Dalandanan"
    ADMIN_EMAIL="admin@dalandanan.gov.ph"
    APP_PORT="8001"
else
    BARANGAY_DB="emr_veinte_reales"
    BARANGAY_NAME="Barangay Veinte Reales"
    ADMIN_EMAIL="admin@vientereales.gov.ph"
    APP_PORT="8000"
fi

echo -e "${CYAN}${BOLD}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         Valenzuela District 1 — Barangay EMR System v2       ║"
echo "║                    Setup Script                               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo -e "  Setting up for: ${BOLD}${BARANGAY_NAME}${NC}"
echo -e "  Database:        ${BOLD}${BARANGAY_DB}${NC}"
echo -e "  Port:            ${BOLD}${APP_PORT}${NC}"
echo ""

# --- Step 1: Python version check ---
echo -e "${BLUE}[1/6] Checking Python version...${NC}"
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ Python 3 not found. Please install Python 3.10+.${NC}"
    exit 1
fi
PY_VER=$(python3 --version | cut -d' ' -f2)
echo -e "${GREEN}✅ Python ${PY_VER}${NC}"

# --- Step 2: Virtual environment ---
echo -e "${BLUE}[2/6] Setting up virtual environment...${NC}"
if [ ! -d "venv" ]; then
    python3 -m venv venv
    echo -e "${GREEN}✅ Virtual environment created.${NC}"
else
    echo -e "${YELLOW}⚠️  Virtual environment already exists.${NC}"
fi

# Activate
if [ -f "venv/Scripts/activate" ]; then
    source venv/Scripts/activate    # Windows Git Bash
elif [ -f "venv/bin/activate" ]; then
    source venv/bin/activate        # Mac/Linux
fi
echo -e "${GREEN}✅ Virtual environment activated.${NC}"

# --- Step 3: Install dependencies ---
echo -e "${BLUE}[3/6] Installing Python packages...${NC}"
pip install --upgrade pip -q
pip install -r requirements.txt -q
echo -e "${GREEN}✅ All packages installed.${NC}"

# --- Step 4: Create .env file ---
echo -e "${BLUE}[4/6] Creating .env configuration...${NC}"
if [ ! -f ".env" ]; then
    # Generate a random secret key
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || echo "change_this_to_random_string_$(date +%s)")

    cat > .env << EOF
# ============================================================
# EMR System v2 — ${BARANGAY_NAME}
# Generated by setup.sh — $(date)
# ============================================================

# Barangay configuration
BARANGAY_DB=${BARANGAY_DB}
BARANGAY_NAME=${BARANGAY_NAME}

# Database — update DB_PASSWORD with your MySQL password
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=

# Security
SECRET_KEY=${SECRET_KEY}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

# Email (optional)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=

# Session
SESSION_TIMEOUT_MINUTES=30

# App
APP_HOST=0.0.0.0
APP_PORT=${APP_PORT}
DEBUG=True
ALLOWED_ORIGINS=http://localhost:${APP_PORT},http://127.0.0.1:${APP_PORT}
EOF
    echo -e "${GREEN}✅ .env file created.${NC}"
    echo -e "${YELLOW}⚠️  Edit .env and set DB_PASSWORD if MySQL requires a password.${NC}"
else
    echo -e "${YELLOW}⚠️  .env already exists. Skipping.${NC}"
fi

# --- Step 5: Database check ---
echo -e "${BLUE}[5/6] Database setup reminder...${NC}"
echo -e "${YELLOW}"
echo "  Before starting the server, make sure you have run schema.sql:"
echo ""
echo "  Option A — MySQL CLI:"
echo "    mysql -u root -p < ../database/schema.sql"
echo ""
echo "  Option B — MySQL Workbench:"
echo "    File → Open SQL Script → schema.sql → Execute"
echo ""
echo "  Then run the password reset script:"
echo "    python reset_admin_password.py"
echo -e "${NC}"

# --- Step 6: Verify files ---
echo -e "${BLUE}[6/6] Verifying project files...${NC}"

REQUIRED_FILES=(
    "main.py"
    "database.py"
    "requirements.txt"
    ".env"
    "reset_admin_password.py"
    "routers/auth.py"
    "routers/users.py"
    "routers/patients.py"
    "routers/analytics.py"
    "routers/reports.py"
    "models/models.py"
    "utils/security.py"
    "middleware/auth.py"
)

ALL_OK=true
for f in "${REQUIRED_FILES[@]}"; do
    if [ -f "$f" ]; then
        echo -e "  ${GREEN}✅ $f${NC}"
    else
        echo -e "  ${RED}❌ MISSING: $f${NC}"
        ALL_OK=false
    fi
done

echo ""
if $ALL_OK; then
    echo -e "${GREEN}${BOLD}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                  ✅ Setup Complete!                           ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo -e "  ${BOLD}Next steps:${NC}"
    echo ""
    echo -e "  1. Run schema.sql in MySQL (if not done yet)"
    echo ""
    echo -e "  2. Reset admin password:"
    echo -e "     ${CYAN}python reset_admin_password.py${NC}"
    echo ""
    echo -e "  3. Start the server:"
    echo -e "     ${CYAN}python -m uvicorn main:app --reload --host 0.0.0.0 --port ${APP_PORT}${NC}"
    echo ""
    echo -e "  4. Open in browser:"
    echo -e "     ${CYAN}http://localhost:${APP_PORT}${NC}"
    echo ""
    echo -e "  5. Login with:"
    echo -e "     Email:    ${CYAN}${ADMIN_EMAIL}${NC}"
    echo -e "     Password: ${CYAN}Admin@123${NC}"
    echo -e "     ${RED}⚠️  Change password immediately after first login!${NC}"
    echo ""

    # Barangay Dalandanan reminder if setting up Veinte Reales
    if [[ "$BARANGAY_ARG" != "dalandanan" ]]; then
        echo -e "  ${BOLD}To also set up Barangay Dalandanan:${NC}"
        echo -e "     ${CYAN}bash setup.sh dalandanan${NC}"
        echo -e "     (Run on port 8001)"
        echo ""
    fi
else
    echo -e "${RED}${BOLD}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║         ❌ Some files are missing — check above.             ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
fi